### ISSUE TITLE
Add open port requirements

### ISSUE THREAD

**Issue by bmicklea** [eclipse/che-docs#128]
We need to outline the ports that need to be opened for Che to work in our docs:
- https://eclipse.org/che/docs/setup/getting-started/index.html#ports
- We should probably add a section for ports on this page too: https://eclipse.org/che/docs/setup/bitnami/index.html

**Comment by JamesDrummond** [comment]
I don't think Bitnami needs it as they make sure these ports are open for user. User would have to actually manually closes them.
