### ISSUE TITLE
Add xtext + language server references to docs

### ISSUE THREAD

**Issue by TylerJewell** [eclipse/che-docs#136]
We get frequently asked about using xtext to build language servers or custom editors.  There was this article written.  In the appropriate places in docs, we should make reference either to this article, or pull out the important elements so that using xtext is clearly explained in the right section.

https://blogs.itemis.com/en/how-to-get-started-with-xtext-language-servers-and-che?success=true

**Comment by themr0c** [comment]
This issue is probably obsolete, and the issue tracker has moved. If needed, open a new issue in https://github.com/eclipse/che/issues.
