### ISSUE TITLE
scripts/base/library.sh: line 555: [: 10: unary operator expected

### ISSUE THREAD

**Issue by nojulian** [eclipse/che-docs#138]
I have a docker enabled ubuntu xenial VM and try to install che, using the 'Quick Start' full syntax command.
However I get the following errors:

`root@ubuntu-xenial:~# docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /vagrant/che/data:/data eclipse/che start`
`WARN: Bound 'eclipse/che' to 'eclipse/che:5.2.2'`
`WARNING: No swap limit support`
`INFO: Proxy: HTTP_PROXY=http://1.2.3.4:8080, HTTPS_PROXY=https://1.2.3.4:8080, NO_PROXY=localhost,127.0.0.1`
`INFO: (che cli): 5.2.2 - using docker 1.13.1 / native`
**`/scripts/base/library.sh: line 555: [: 10: unary operator expected`**
**`/scripts/base/library.sh: line 308: 2: unbound variable`**
`root@ubuntu-xenial:~#`

**Comment by TylerJewell** [comment]
This is a very interesting error.  Can you:
1. Wipe all of your docker images and rerun?
2. Also show us what happens if you add `--trace` to the output?

Thanks!

**Comment by TylerJewell** [comment]
The error - btw - comes from here https://github.com/eclipse/che/blob/5.2.2/dockerfiles/base/scripts/base/library.sh#L555-L557.  This tells me that perhaps networking is not configured properly within your VM as we are failing when getting into DockerHub.  If you add `--skip:network` or `--fast` does that change the outcome?

**Comment by nojulian** [comment]
using --trace has this ending:

`INFO:      a. Add '--fast' to any command
++ printf 'INFO: %b %b\n' '' '     a. Add '\''--fast'\'' to any command'
+ log INFO: a. Add ''\''--fast'\''' to any command
+ [[ true = \t\r\u\e ]]
+ is_log
+ '[' true = true ']'
+ return 0
+ echo INFO: a. Add ''\''--fast'\''' to any command
+ return 2
+ cleanup
+ RETURN_CODE=2
+ '[' 2 -eq 3 ']'`

so i guess it is about that equality there the error.
The thing is that using --fast it worked.
Executing **without** --fast switch I had these images:

root@ubuntu-xenial:~# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
eclipse/che         latest              dd03817a34ff        13 days ago         51.1 MB
eclipse/che-ip      5.2.2               d3ac85b1a8ab        2 weeks ago         4.81 MB
alpine              3.4                 0766572b4bac        7 weeks ago         4.8 MB

and after issuing the --fast I had these:
root@ubuntu-xenial:~# docker images
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
eclipse/che-server   5.2.2               75f655517886        13 days ago         316 MB
eclipse/che          latest              dd03817a34ff        13 days ago         51.1 MB
eclipse/che-init     5.2.2               e9b30eaa7d83        2 weeks ago         55 MB
eclipse/che-ip       5.2.2               d3ac85b1a8ab        2 weeks ago         4.81 MB
alpine               3.4                 0766572b4bac        7 weeks ago         4.8 MB
docker/compose       1.8.1               5edc87ec4325        4 months ago        59.2 MB

Thanks :+1:
