### ISSUE TITLE
Che docs don't have HTML titles

### ISSUE THREAD

**Issue by jonahkichwacoders** [eclipse/che-docs#140]
A lack of HTML title tag makes navigation harder than necessary to navigate the help, especially when multiple pages are open as shown in this screenshot:

![che-docs-no-title](https://cloud.githubusercontent.com/assets/679236/22972010/b9a7b138-f36f-11e6-8b70-1c617a3bbcd4.png)

PS Google search results are using its own smarts to generate titles, so a search like` eclipse "che in che"` does bring https://eclipse.org/che/docs/tutorials/che-in-che/index.html as the first result with the apparent title of _Che in Che - Eclipse_.

**Comment by TylerJewell** [comment]
Thanks for the fix.
