### ISSUE TITLE
Do you support Swift?

### ISSUE THREAD

**Issue by TofPlay** [eclipse/che-docs#143]
Interesting tool 🙂
Do you support Swift?

From [Swift.org](https://swift.org/about/#platform-support):
"On December 3, 2015, the Swift language, supporting libraries, debugger, and package manager were published under the Apache 2.0 license with a Runtime Library Exception, and Swift.org was created to host the project.
Open-source Swift can be used on Linux to build Swift libraries and applications. The open-source binary builds provide the Swift compiler and standard library, Swift REPL and debugger (LLDB), and the core libraries, so one can to jump right in to Swift development."

**Comment by TylerJewell** [comment]
Hi - thanks for the support of the project.

You should open tickets on Che's primary repo.  Here is a list of past issues about swift - there is also a Swift stack built into Che - https://github.com/eclipse/che/search?q=swift&type=Issues&utf8=%E2%9C%93
