### ISSUE TITLE
Add import in IntelliJ to Setup IDE page

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#156]
We have a section where we are explaining how to setup super dev mode for Intellij, but we are not having a section to explain how to import Che sources in it.

Should add the instructions.

**Comment by slemeur** [comment]
https://github.com/eclipse/che/issues/4226#event-976088813

**Comment by themr0c** [comment]
This issue is probably obsolete, and the issue tracker has moved. If needed, open a new issue in https://github.com/eclipse/che/issues.
