### ISSUE TITLE
Provide explanations about how factories handled while upgrading to a new Che version

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#175]
We need to add into the factory documentation a paragraph explaining how factories are persisted when upgrading Che to a newer version.

**Comment by slemeur** [comment]
@mshaposhnik : Could you briefly explain how factories are affected when Che is upgraded? 

From my understanding, the existing factories are persisted into the database. Similarly to the existing workspace and all user's data, the upgrade of Che does not interfere with existing factories.

**Comment by mshaposhnik** [comment]
@slemeur Yes your vision is correct

**Comment by slemeur** [comment]
Thanks added to docs.
