### ISSUE TITLE
Add more details about how to register a new syntax highlighting 

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#192]
Following the issue: https://github.com/eclipse/che/issues/4696

We need to:
- describe where the add the hook to register content type and highlighting in orion (see https://github.com/eclipse/che/pull/1392)
- implement a sample into our plugins samples: https://github.com/eclipse/che/tree/master/samples/sample-plugin-filetype/che-sample-plugin-filetype-ide

**Comment by themr0c** [comment]
This issue is probably obsolete, and the issue tracker has moved. If needed, open a new issue in https://github.com/eclipse/che/issues.
