### ISSUE TITLE
Cannot find Profile > Preferences > SSH > VCS

### ISSUE THREAD

**Issue by JeffBship** [eclipse/che-docs#193]
https://github.com/eclipse/che-docs/blob/master/src/main/_docs/use-che-as-an-ide/ide-git-svn.md gives directions to go to  Profile > Preferences > SSH > VCS to generate a key.

The only profile I can find is https://codenvy.io/dashboard/#/account, and that is nothing related to keys.

**Comment by JeffBship** [comment]
"You need to be in a workspace/IDE. So create a workspace from ready-to-go stack blank then access this menu. This should really be in the dashboard too. Please provide an issue at https://github.com/eclipse/che/issues for this enhancement request if you would like it."

James Drummond, P.E., LEED AP BD+C // Codenvy // Release Manager // jdrummond@codenvy.com

**Comment by bmicklea** [comment]
Created an enhancement request based on what I think you're looking for @JeffBship 

https://github.com/eclipse/che-docs/issues/200
