### ISSUE TITLE
Add ability to set keys in user dashboard

### ISSUE THREAD

**Issue by bmicklea** [eclipse/che-docs#200]
For new users it can be confusing to find key settings (which affect all workspaces) in the profile menu of the IDE with a specific workspace open.

It should be possible to set cross-workspace profile settings in the user dashboard and have them shown in the IDE profile panel either as RO values, or synced between the two panels.

From: https://github.com/eclipse/che-docs/issues/193

**Comment by themr0c** [comment]
This issue is probably obsolete, and the issue tracker has moved. If needed, open a new issue in https://github.com/eclipse/che/issues.
