### ISSUE TITLE
Refactoring docs PR has erased and override some documentation 

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#215]
Refactoring docs PR https://github.com/eclipse/che-docs/pull/149
has override documentation for intelligent commands.

There are probably other pages that have been updated between the time the PR has been opened, and the time it was merged.

**Comment by slemeur** [comment]
I found that we are missing the workspace JSON Model page

**Comment by themr0c** [comment]
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.
