### ISSUE TITLE
Add supporting doc for embedded iframe with javascript

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse/che-docs#226]
Add supporting doc about `plugin-framedjs-archetype`.

![framedjs](https://cloud.githubusercontent.com/assets/1655894/25891955/7fd0819e-357b-11e7-8736-7e28437de9ed.png)

**Comment by themr0c** [comment]
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.
