### ISSUE TITLE
Need to add --privileged to docker run command

### ISSUE THREAD

**Issue by gpeavy** [eclipse/che-docs#228]
When trying to start che locally I needed to add the --privileged argument to mount /var/run/docker.sock

**Comment by TylerJewell** [comment]
This should never be required.  You will need to provide more details on the scenario about your environment.

**Comment by gpeavy** [comment]
Environment:
Bare metal install of Centos Atomic Host 7.
Also installed openshift origin v1.5.0
Ran the docker run command as root directly on the atomic host and did not try to setup che through openshift.

**Comment by TylerJewell** [comment]
This is not a docs issue - you can consider moving this over to the Eclipse Che core issue. It may have to do with permissions or other configuration of your system.
