### ISSUE TITLE
Minimum version of CHE to use Archetype tool

### ISSUE THREAD

**Issue by vnea** [eclipse/che-docs#236]
Hello,

In the [presentation of the **Archetype** tool](https://www.eclipse.org/che/docs/assemblies/archetype/index.html), it is said minimum version is **5.7.0**:

> **# Eclipse Che 5.7.0 or higher**
> docker run -it --rm ...

But in [**Assembly Dev Lifecycle** docs](https://www.eclipse.org/che/docs/assemblies/assembly-lifecycle/index.html#generate), all commands use **5.4.0** version:

> docker run -it --rm
>      -v /var/run/docker.sock:/var/run/docker.sock
>      -v /c/archetype:/archetype
>      -v /c/tmp:/data
>      -v /c/Users/Tyler/.m2/repository:/m2
>        **eclipse/che-cli:5.4.0**
>          archetype generate

So is it **5.4.0** or **5.7.0** the min version to use **Archetype** ?
I can do a PR then.

**Comment by slemeur** [comment]
Hi @vnea !
Nice catch.

We have [integrated](https://github.com/eclipse/che/pull/4179) the archetype tool in 5.7.0. So the right minimum version to be mentioned in the docs is 5.7.0 or higher indeed.

Thanks !

**Comment by vnea** [comment]
You're welcome, the PR is done.
