### ISSUE TITLE
ubuntu_jdk8 docker image on docker hub is not in sync with Dockerfile

### ISSUE THREAD

**Issue by Bassinator** [eclipse/che-docs#245]
the image on docker hub has openjdk installed not the oracle version.
the codenvy/ubuntu_jdk8 image is correct
Pleas upload correct version

**Comment by TylerJewell** [comment]
I am not following this issue.

The version on docker hub is the correct version and matches what is in eclipse/che-dockerfiles.

**Comment by benoitf** [comment]
@Bassinator FYI the images are now on `eclipse/` namespace and not anymore within `codenvy/` namespace

**Comment by benoitf** [comment]
new: https://hub.docker.com/r/eclipse/ubuntu_jdk8/
old: https://hub.docker.com/r/codenvy/ubuntu_jdk8/

**Comment by benoitf** [comment]
closing as it is in sync

**Comment by Bassinator** [comment]
Sorry, did not see the updates on this issue. And I do not agree. Perhaps I am getting something wrong. But I pulled both images eclipse/ubuntu_jdk8 and codenvy/ubuntu_jdk8. Java version on the eclipse image is openjdk wich does not match the dockerfile on docker hub ?

You can see it in my console output below? Am I getting something wrong?
```
bastians-macbook-air:~ bastian$ docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
eclipse/ubuntu_jdk8   latest              cc30fc7d858c        4 weeks ago         716MB
codenvy/ubuntu_jdk8   latest              4074bfc5705b        9 months ago        668MB
bastians-macbook-air:~ bastian$ docker run 4074bfc5705b java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
bastians-macbook-air:~ bastian$ docker run cc30fc7d858c java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
bastians-macbook-air:~ bastian$ docker run 4074bfc5705b ls /opt
jdk1.8.0_45
bastians-macbook-air:~ bastian$ docker run cc30fc7d858c ls /opt
bastians-macbook-air:~ bastian$ 
```

**Comment by benoitf** [comment]
@Bassinator 
you said

> Java version on the eclipse image is openjdk wich does not match the dockerfile on docker hub ?

eclipse/ubuntu_jdk8 is built with Dockerfile
https://github.com/eclipse/che-dockerfiles/blob/master/recipes/ubuntu_jdk8/Dockerfile

**Comment by Bassinator** [comment]
Hello, 
Thanks and yes. But:
What I am trying to point out, is that on docker-hub, a different docker file is uploaded, which does not correspond to the image. See
https://hub.docker.com/r/eclipse/ubuntu_jdk8/~/dockerfile/

**Comment by benoitf** [comment]
@eivantsov is there a way to remove/update this file from dockerhub ?
