### ISSUE TITLE
Automatic scroll only works once

### ISSUE THREAD

**Issue by martinambrus** [eclipse/che-docs#250]
Hi guys,

I've been trying out Che at CodeEnvy and every time I try to enable automatic scrolling of the terminal output (usually when the workspace is starting), it always stops after the first auto-scroll.

This is what I'm talking about (the bottommost leftmost button):

![image](https://user-images.githubusercontent.com/7406402/27732894-b7b16b88-5d93-11e7-815d-a37838b7bc48.png)

It doesn't matter whether I click that button later or not, scrolling would not start working at all.

This is on latest Chrome (Version 59.0.3071.115 (Official Build) (64-bit), Ubuntu 16.04) but had the same results on a few previous Chrome versions as well. I'd guess it's not a browser-specific issue.

**Comment by slemeur** [comment]
Hi @martinambrus ! 

Thanks for reporting the issue. 
We have identified this issue here: https://github.com/eclipse/che/issues/5130 

I'm closing this one as already cross-referenced on Che repo.
