### ISSUE TITLE
Permission denied when using archetype

### ISSUE THREAD

**Issue by jonahkichwacoders** [eclipse/che-docs#254]
Trying, on Linux, to generate an archetype according to the directions in https://www.eclipse.org/che/docs/assemblies/assembly-lifecycle/index.html#generate leads to the following error (as pretty much the only output):

```
/scripts/base/startup_02_pre_docker.sh: line 670: /data/test: Permission denied
```
Full command and output I used:

```
$ docker run -it --rm   -v /var/run/docker.sock:/var/run/docker.sock   -v /scratch/che/archetype:/archetype   -v /scratch/che/che8080tmp:/data   -v ~/.m2/repository:/m2   -v /etc/group:/etc/group:ro       -v /etc/passwd:/etc/passwd:ro       --user=1000:1000        --group-add 999     eclipse/che-cli:5.14.0       archetype generate
WARNING: No swap limit support
/scripts/base/startup_02_pre_docker.sh: line 670: /data/test: Permission denied
```

After some digging around it turns out that if docker creates the host directory it gets owned by root and therefore specifying the `--user` means that the scripts get permission denied.

The workaround is to create all the host directories before doing `docker run`, so in the above example:

```
mkdir /scratch/che/che8080tmp
mkdir /scratch/che/archetype
docker run ...
```

**Comment by TylerJewell** [comment]
@benoitf - didn't you run into this issue when you were doing early tests of the archetypes on linux?  We had a work around for this that did not include creating directories in advance.  What was it?  I notice that Jonah is submitting pull requests for the docs discussing more advanced use cases for archetypes on linux, but need to make sure that the syntax being proposed is universal and not specific to his linux machine.

**Comment by dmytro-ndp** [comment]
Another possible workaround is to mount volumes **data**, **repo**, ... with `:z` flag.

**Comment by skabashnyuk** [comment]
archetypes in che 6 has been deprecated please use https://github.com/che-samples

**Comment by stewartshea** [comment]
I believe you can also work around this by setting the following selinux context on your che directory: 

On a fedora/centos/rhel: 
```
chcon -Rt svirt_sandbox_file_t ~/che
```
I haven't gone beyond the startup yet, but the container started up successfully with the above.
