### ISSUE TITLE
Broken link in 'SDK Language Server Protocol' article

### ISSUE THREAD

**Issue by rcjsuen** [eclipse/che-docs#268]
[assemblies-sdk-language-server-protocol.md](https://github.com/eclipse/che-docs/blob/f4390cd14489fa9bafdad726e371a759b9b6389e/src/main/_docs/assemblies/assemblies-sdk-language-server-protocol.md) has a section that refers to `LanguageServerDescription`. Unfortunately, the link is broken because the file has been moved since whenever that section was last updated. It feels to me that Che's documentation should be using [permanent links](https://help.github.com/articles/getting-permanent-links-to-files/) instead of simply referring to the latest version on master because (as shown in this case) files may be moved.

**Comment by slemeur** [comment]
Hi @rcjsuen ! Thanks for reporting the issue. 
While the LSP was refactored, the documentation was not updated - that was the issue.

**Comment by slemeur** [comment]
Fixed by #269
