### ISSUE TITLE
Editor keybindings docs needs to be updated

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#276]
The following documentation: https://eclipse.org/che/docs/ide/editor-settings/index.html needs to be updated accordingly with the new way to configure the editor keybindings.

Since 5.6 - and the following issue https://github.com/eclipse/che/pull/4394 : the keybindings are getting their dedicated wizard available from `Assistant > Keybinding` menu.

**Comment by themr0c** [comment]
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.
