### ISSUE TITLE
SDK Action documentation not up to date

### ISSUE THREAD

**Issue by hkolvenbach** [eclipse/che-docs#278]
https://www.eclipse.org/che/docs/assemblies/sdk-actions/index.html

CurrentProject does not exist in `org.eclipse.che.ide.api.app` anymore. It should probably be `AppContext.getRootProject()`

**Comment by bmicklea** [comment]
@eivantsov is this update part of the new docs you're working on?

**Comment by themr0c** [comment]
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.
