### ISSUE TITLE
Script wait-che.sh depends on tool jq

### ISSUE THREAD

**Issue by ppitonak** [eclipse/che-docs#282]
1. follow the instructions in https://www.eclipse.org/che/docs/setup/openshift/index.html#deploy-che-on-minishift
2. script wait-che.sh failed for me with following error

```
[CHE] This script is going to wait until Che is deployed and available
[CHE] [ERROR] Command line tool jq (https://stedolan.github.io/jq) is required but it's not installed. Aborting.
```

This dependency should be documented properly

**Comment by bmicklea** [comment]
We've added the reference to jq in the pre-reqs now: https://www.eclipse.org/che/docs/setup/openshift/index.html#pre-reqs

Thanks for pointing this out!
