### ISSUE TITLE
How to work on a project located in a local directory? (Not via Github or importing a zip file)

### ISSUE THREAD

**Issue by ghost** [eclipse/che-docs#336]
Sorry if this question has an obvious answer, but I haven't been able to figure out it so far.

**What I want to do**

Work on a project that I have in a local directory (say it's located in `/User/stiancognite/dev/myproject`). I want to start eclipse che and be able to work on my project.

I'm very used to developing R using the `rocker/rstudio` (https://hub.docker.com/r/rocker/rstudio/) Docker images. There I can start the container like this: `docker run -d -p 8787:8787 -v /Users/stiancognite/dev/myproject:/home/rstudio/myproject rocker/rstudio`. Then I can go to localhost:8787 and open the folder that has my project (i.e. `/home/rstudio/myproject`). Would a similar workflow be possible with Eclipse Che?

**What I've tried**

1. [This page](https://www.eclipse.org/che/docs/ide/import-a-project/index.html) says `Open a terminal in the IDE and create folders in the /projects directory`, which lead me to think that I should be able to open a project if I've added it to `/projects`. So I tried this: `docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v /Users/cognite/dev/tmp:/data -v /Users/stiancognite/dev/myproject:/projects/myproject eclipse/che:latest start`. But when I try to create a new workspace I don't see a way to use that project. If I choose to start with a blank project, and then click "Import" in the IDE I don't see any way to use a local folder. I see options to use a GitHub repository or download a zip file.

2. [This page](https://www.eclipse.org/che/docs/ide/sync/index.html) lead me to believe that I could accomplish the same thing by placing my project directory in `/sync`. I tried this: `docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v /Users/cognite/dev/tmp:/data -v /Users/stiancognite/dev/myproject:/sync eclipse/che:latest start`, but that gave me the same result as in my first attempt.

**Comment by bmicklea** [comment]
I don't think there's really a way to do this. Is there a reason you don't want to use git?  Keeping things in a local directory and untracked via a source code repository is a dangerous practice - all you need is a single failure or corruption to potentially lose all your work.

I'm closing this but you can comment to re-open if you want.

**Comment by stianlagstad** [comment]
Thank you for answering. I like my workflow with Rstudio in a docker image:
- Change files and build in the browser IDE through the running docker container
- Use git on my own machine (with all my config, shell tools, ++) to manage version control of the changes I'm doing in the IDE

If I'm to get a hold of my project within eclipse che through git then I'd have to commit stuff and work with git within eclipse che - right? And then I wouldn't have the shell tools I have locally.

**Comment by bmicklea** [comment]
You can use git from the command line in Che. It may not (by default) have everything you're looking for, but you can create a machine recipe with the shell tools and things you need so that using git from the terminal in Che is equivalent to using it locally. That way everything is together (and you could even create Che commands to automate some of the more complex git operations you're doing manually now).

**Comment by vincenzocaselli** [comment]
I have the same need and I wanted to describe why I cannot count on the Git solution.
Locally I have projects (Angular+Java) that have requirements like the following:
* access to local files on the file system, outside the project itself
* access to local databases
* access to external resources via VPN
and similar.

Normally I use Eclipse IDE and occasionally VS Code or other IDEs opening the same src files, make some modification, run it to test and so on. When the modification is successful then commit and push.
I would like to use Eclipse Che too in the same way.
Is there some way or workaround to do this?
Thank you very much
Vincenzo

**Comment by themr0c** [comment]
This issue is probably obsolete, and the issue tracker has moved. If needed, open a new issue in https://github.com/eclipse/che/issues.
