### ISSUE TITLE
block download

### ISSUE THREAD

**Issue by crfcarlos** [eclipse/che-docs#338]
I am using eclipse che 6.00-m4 multi user and would like to know how to lock the work space to not allow download of the project to users, Is this possible?

**Comment by bmicklea** [comment]
You can customize the Che UI to remove the download as zip option, but users would still be able to copy and paste at will plus (depending on how your git credentials are setup) they may be able to clone to another location.

If that doesn't answer the question feel free to reopen it with another comment.
