### ISSUE TITLE
IDE Extensions link broken - receiving 404 File not found error

### ISSUE THREAD

**Issue by RanjithRV** [eclipse/che-docs#389]
When I tried to check what sort of plugins are supported by Che, I got redirected to a '404 File not found error'

Link Source: https://www.eclipse.org/che/extend/  (under IDE extensions) 
Redirected to: https://www.eclipse.org/che/docs/6/che/docs/ide-extensions-js.html

<img width="838" alt="redirect-page" src="https://user-images.githubusercontent.com/22077715/38598474-26f57892-3d7a-11e8-8cc0-f6a3f987fbce.png">
<img width="1168" alt="url source" src="https://user-images.githubusercontent.com/22077715/38598478-290b0746-3d7a-11e8-8f34-48043a8bb918.png">

**Comment by eivantsov** [comment]
@RanjithRV it should be already fixed.
