### ISSUE TITLE
Broken links in nav and header

### ISSUE THREAD

**Issue by colewhite** [eclipse/che-docs#427]
Appears to be global, no matter where you are in the documentation.  Tested from https://www.eclipse.org/che/docs/index.html

1. 404 in header: "Docs 5.x" -> https://www.eclipse.org/che/docs/5/che/docs
2. Empty release notes: "Release Notes" does not link to the Medium blog
3. Bad address in head file -> http://0.0.0.0:4000/feed.xml  Looks like a variable is getting defined incorrectly here: https://github.com/eclipse/che-docs/blob/master/src/main/_includes/head.html#L41

**Comment by slemeur** [comment]
cc @eivantsov ^^

**Comment by themr0c** [comment]
We are closing this issue as it is appearing outdated.
