### ISSUE TITLE
Create page for Terminal and Processes panel

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#46]
Similar to the pages on this section:
https://github.com/codenvy/che-docs/tree/master/src/main/_docs/use-che-as-an-ide

We need to add a new page about the Process panel. This panel is not covered in any docs.
Items to cover:
- How to get a terminal
- How to split
- Various display options in the toolbar
- Double click on panel for the fullscreen mode

**Comment by JamesDrummond** [comment]
@slemeur Some of these are already done in https://eclipse.org/che/docs/ide/editor-settings/index.html

**Comment by themr0c** [comment]
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.
