### ISSUE TITLE
Double underscore rendered as italic

### ISSUE THREAD

**Issue by eivantsov** [eclipse/che-docs#478]
@rkratky perhaps you know the answer

I can see that things like 

```
`CHE_WORKSPACE_DEFAULT__MEMORY__LIMIT__MB`
```

are rendered as:

![image](https://user-images.githubusercontent.com/5337267/45145264-eea27580-b1c8-11e8-947d-5a162fff2cca.png)

What's the right way to have inline code in asciidoc?

**Comment by rkratky** [comment]
Thanks @dneary. Just submitted a PR with a fix.

Note: For future reference, the use of double dollar signs is deprecated. See https://asciidoctor.org/docs/user-manual/#pass-macros
