### ISSUE TITLE
Move user deletion docs from OpenShift config to User Management docs

### ISSUE THREAD

**Issue by ghost** [eclipse/che-docs#483]
This does not looks like the right place for such docs https://github.com/eclipse/che-docs/blob/234ffc2670dfa8222eb70db3eb362bb25cd641aa/src/main/pages/setup-openshift/openshift-admin-guide.adoc#gdpr

**Comment by themr0c** [comment]
We are closing this issues because we believe it is outdated.

https://www.eclipse.org/che/docs/che-7/removing-user-data/
