### ISSUE TITLE
Links are broken on eclipse.org/che/docs

### ISSUE THREAD

**Issue by l0rd** [eclipse/che-docs#484]
All links in the [landing page](https://www.eclipse.org/che/docs/) don't work (that's true in other pages as well).

For example the link to [quick-start](https://www.eclipse.org/che/docs/quick-start) returns 404. The same links work when suffixed by ".html".

Images links are broken too.

**Comment by eivantsov** [comment]
/@rkratky it happened after conversion of docs to asciidoc. Can you please investigate asap?

**Comment by l0rd** [comment]
Links work now, and images are back too
