### ISSUE TITLE
Need instructions for building and previewing docs other than the run.sh file

### ISSUE THREAD

**Issue by dneary** [eclipse/che-docs#488]
I would like to build and preview doc changes without Docker. I would like to do it in a Che factory. Both of these require knowing what packages to install, and which command lines to run, and (for a Docker image) which Dockerfile to use. The docs instructions currently point at a Docker image, with no instructions on how to rebuild it. I would expect there to be at least a Dockerfile to use, and ideally a set of commands to run on a regular Linux host to check the docs with Jekyll.

Thanks for the AsciiDoc migration work!

**Comment by nickboldt** [comment]
1. install ruby & deps:

````
sudo yum install ruby ruby-devel @development-tools
````

2. Set up env

````
echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
echo 'export GEM_HOME=$HOME/gems' >> ~/.bashrc
echo 'export PATH=$HOME/gems/bin:$PATH' >> ~/.bashrc
source ~/.bashrc
````

3. Install jekyll, build site

````
gem install jekyll bundler jekyll-asciidoc
bundle install

cd /path/to/che-docs/src/main/
mkdir -p _site
jekyll serve # includes jekyll build, into _site folder
````

Docs will be on http://127.0.0.1:4000/

**Comment by themr0c** [comment]
We are closing this issues because we believe it is outdated.
