### ISSUE TITLE
Support building docs without need for commandline docker

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che-docs#494]
In order to build che-docs this in NCL (as part of productization), it needs to be able to run without launching a separate docker container [1] during the build. 

[1] https://hub.docker.com/r/robkratky/che-docs/

We could implement something akin to the 'docker' profile in eclipse che dashboard [2] or the workspace-loader [3].

[2] https://github.com/eclipse/che/blob/master/dashboard/pom.xml#L108
[3] https://github.com/eclipse/che/blob/master/workspace-loader/pom.xml#L73

Of course this will also assume that the NCL slave nodes have jekyl installed.

**Comment by dneary** [comment]
This is a duplicate of issue #488 

I am looking for non-Docker instructions for another reason - if we can start from a pristine CentOS instance and install prerequisites, I can make a Dockerfile for a base image, and produce a factory more easily, and enable people to work on docs in che.openshift.io

**Comment by nickboldt** [comment]
PR merged so closing.
