### ISSUE TITLE
Miscallenous typos/issues

### ISSUE THREAD

**Issue by marechal-p** [eclipse/che-docs#500]
https://github.com/eclipse/che-docs/blame/master/src/main/pages/setup-docker/docker-multi-user.adoc#L15

The link to [Ephemeral ports](https://en.wikipedia.org/wiki/Ephemeral_port) adds a `)` character at the end of the URL for some reason, and sends us on a 404.

---
https://github.com/eclipse/che-docs/blame/master/src/main/pages/setup-docker/docker-single-user.adoc#L53

`CHE_DOCKER_ALWAYS_PULL_IMAGE` has `PULL` in italics, when I think it is because it has `_` around it, and markdown assumes it is for formatting, but it is not.

**Comment by rkratky** [comment]
@marechal-p Thanks for reporting this. I just submitted a PR that fixes the first problem.

The second problem is solved by https://github.com/eclipse/che-docs/pull/492 (waiting to be merged).
