### ISSUE TITLE
Text about "boot2docker" in the Single-User: Install on Docker section

### ISSUE THREAD

**Issue by supriya-bharadwaj** [eclipse/che-docs#520]
There is mention of **boot2docker** in the **Single-User: Install on Docker** section. Isn't **boot2docker** deprecated?
Article at: https://www.eclipse.org/che/docs/docker-single-user.html
Section title: Run Che on Public IP Address

**Comment by themr0c** [comment]
We are closing this issues because we believe it is outdated.
