### ISSUE TITLE
Do not suggest turning of selinux 

### ISSUE THREAD

**Issue by peterducai** [eclipse/che-docs#607]
#Description
at https://www.eclipse.org/che/docs/docker-single-user.html and https://github.com/eclipse/che-docs/blob/master/src/main/pages/setup-docker/docker-single-user.adoc you suggest turning of Selinux which is completely wrong

##Solution

instead of turning off selinux, turn it off only for che (make it unconfined)

> chcon -t unconfined_exec_t /usr/sbin/che

**Comment by peterducai** [comment]
this doesnt look to be fixed

**Comment by peterducai** [comment]
do you really ignore security????

**Comment by rkratky** [comment]
@peterducai, apologies. We just don't have the capacity to fix all issues as quickly as we would like to. (Also, your suggested solution wouldn't work; a) Che is run out of a container, and the SELinux issue is on the host, not within the container, b) there's no such binary as `/usr/sbin/che`.)

@eivantsov, we should document a way to make Che work well with SELinux enabled. I previously tried the various workarounds suggested in GH issues, but none of them seem to be reliable. What's the best way to deal with this?

**Comment by themr0c** [comment]
We are closing this issues because we believe it is outdated. 

(I see no mention of Selinux in current docs.)
