### ISSUE TITLE
Add documentation about creating a Che 6 image

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#632]
We currently have some documentation related to the creation of a stack, but it is a bit spread and one can not understand the whole sequence (creating recipe, then stacks, then registering the stack). 

We would like to introduce new kind of documentation related to the creation of a stack. Those should be more "tutorial"/"scenario" based, to better guide the user or the administrator into the creation of a stack.

There are few use cases we would like to cover:
- **As a user, I want to create my own stack for my project**: This is a general question. I'm a new user of Eclipse Che, and I have my project. I want to create a dedicated stack for it. I could create my stack using one of those provided by default by Eclipse Che.
- **As a user, I have my dockerfile for my project and I want to use it into Eclipse Che**: That is a second general scenario. A user will need to know what are the requirements in the 
- **As a admin, I want to create a stack and make it available to all the users**: That is a third general use case which needs to be documented for an admin. Once a stack has been created, an admin will need to know how to enable it to other users.

Those guides must include:
- [ ] Explanation about what is needed in the images (for Che, for the LS, for the container to stay alive...).
- [ ] Complete flow for creating an image, from writing the recipe to publishing the image on a container registry (which could be private).
- [ ] Links to samples stacks, recipes, images on dockerhub, samples.
- [ ] Using the UI to create a stack.
- [ ] Using API for registering a stack for all users.
- [ ] Covering the update aspect of a stack.
- [ ] Tips & Tricks (for anything we know that should be shared with the users/admins)
- [ ] How to propose the stack to Eclipse Che (with link to sample PRs)
- [ ] How to register a project sample with a stack

**Comment by rkratky** [comment]
@slemeur, thanks for the outline. Why is this limited to Che 6?

**Comment by slemeur** [comment]
The stacks and the requirements will be different on Che 7. So for now, I'd like to get that in place for the current version.
But we can surely duplicate the issue for Che 7 too :)

**Comment by eivantsov** [comment]
I'm afraid there's no easy way to add a custom sample app. To do that you will need access to Che master PV. And Che master may have no PV attached at all, for example to be able to use Rolling update strategy (in case storage driver/class does not support read write many)

**Comment by slemeur** [comment]
Ack. Something that needs to be improved into the Che then.

**Comment by themr0c** [comment]
We are closing this issues because we believe it is outdated.
