### ISSUE TITLE
OpenShift plugin install page doesn't explain how to copy the binaries

### ISSUE THREAD

**Issue by rimolive** [eclipse/che-docs#65]
Link: https://www.eclipse.org/che/docs/openshift/config/index.html

It only mentions to download the Binaries and that's it. What should I do with it?

**Comment by JamesDrummond** [comment]
Related to https://github.com/eclipse/che-docs/issues/76

**Comment by eivantsov** [comment]
@JamesDrummond i do not think this is a correct title. We need a few lines on how to start Tomcat and that's it. 

@bmicklea the label should be docs not bug

**Comment by bmicklea** [comment]
Since this is a docs repo we'll use `bugs` to indicate a gap in docs that shouldn't be there and `enhancement` to indicate an expansion of the docs.

**Comment by JamesDrummond** [comment]
@eivantsov I think Ilya is working on this right? I think bug label might be right in this case as brad mentioned. Docs is general term.

**Comment by themr0c** [comment]
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.
