### ISSUE TITLE
Maven errors while building OpenShift plugin

### ISSUE THREAD

**Issue by rimolive** [eclipse/che-docs#66]
I can't build the OpenShift plugin as mentioned in https://www.eclipse.org/che/docs/openshift/config/index.html.

The whole maven output is in the gist below:

https://gist.github.com/rimolive/77f9d9e400a5f9105e52a2306103c5ee

**Comment by JamesDrummond** [comment]
Related to https://github.com/eclipse/che-docs/issues/76

**Comment by themr0c** [comment]
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.
