### ISSUE TITLE
Document requirements to work remote Theia plugin feature.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse/che-docs#670]
@eivantsov investigated that remote Theia plugin doesn't work on the minikube/minishift. The problem was that containers had no ability to communicate between each other (che and remote plugin). It was solved by starting `minikube start` with --docker-opt userland-proxy=false. We need apply this information to docs.

**Comment by AndrienkoAleksandr** [comment]
https://github.com/eclipse/che/issues/12526#issuecomment-458489204

**Comment by themr0c** [comment]
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.
