### ISSUE TITLE
Add docs for PHP Composer project generation

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#68]
Refer to PR: 
https://github.com/eclipse/che/pull/3726

Update PHP tutorial:
https://www.eclipse.org/che/docs/tutorials/php/index.html

**Comment by riuvshin** [comment]
what is the status of this ?  should we drop 5.1.0 milestone?

**Comment by slemeur** [comment]
Let's postpone for now and see how we could update the PHP tutorial
https://www.eclipse.org/che/docs/tutorials/php/index.html

Maybe @kaloyan-raev could help us and contribute on this doc issue.

**Comment by kaloyan-raev** [comment]
@slemeur This is still in my todo list, but I won't be able to work on this in the next 10 days.

**Comment by kaloyan-raev** [comment]
I proposed an update of the existing PHP tutorial in #113. It just barely touches the Composer support in Che. I think we should have a separate page for the Composer support.

**Comment by bmicklea** [comment]
I agree @kaloyan-raev and I also reviewed, approved and merged you PR #113 (I hope you don't mind that I merged it but we are pushing for 5.2 release soon and I know it's getting late in the day for you).

**Comment by kaloyan-raev** [comment]
@bmicklea Thanks for merging! I will draft a separate doc page about Composer today.

**Comment by kaloyan-raev** [comment]
PR #116
