### ISSUE TITLE
Update Che Docs site

### ISSUE THREAD

**Issue by sleshchenko** [eclipse/che-docs#681]
Update Che Docs site https://www.eclipse.org/che/docs/ was not updated since `Nov 28, 2018`. 
From that time there were many updates that are needed for users, like for deploying Che on Kuberentes.

**Comment by benoitf** [comment]
I'm working on this

**Comment by benoitf** [comment]
@sleshchenko should be fixed now, please close if OK with you

**Comment by benoitf** [comment]
linking https://github.com/eclipse/che-docs/issues/682

**Comment by benoitf** [comment]
already done
