### ISSUE TITLE
Add documentation for Language Server development

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#70]
We have explained Language Server for the end user but at this moment we don't have any development workflow explanations.

We need to add a new page under the section "Developer Guide - IDE Plugins" where we explain:
- Basics of Language Server Protocol (this would point to protocol specification)
- How to package and try a language server as a Che module
- How to register language server with project type of file type
- How to create a custom assembly to try the language server
- How to create a PR to include a language server to default Che assembly

See community requests like: https://github.com/eclipse/che/issues/3772#event-926099718

**Comment by tolusha** [comment]
Depends on https://github.com/codenvy/che-docs/issues/70
