### ISSUE TITLE
Che 7 GA: Need to create docs for "Hosted Che" section

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che-docs#715]
Potential structure:
- what is "Hosted Che"?
- registration process (including GH account linking)
- Information about available resources (RAM / CPU)
- Creating and starting Che 7 workspace on Hosted Che
- link to SaaS Cloud https://www.eclipse.org/che/getting-started/cloud/ 
- link to FAQ - https://github.com/redhat-developer/rh-che/blob/master/FAQ.adoc

**Comment by ibuziuk** [comment]
@slemeur @l0rd @rkratky wdyt?

**Comment by rkratky** [comment]
@ibuziuk, could you please add this content to https://github.com/eclipse/che-docs/blob/master/src/main/pages/che-7/overview/assembly_hosted-che.adoc?

**Comment by ibuziuk** [comment]
@rkratky you mean structure?

**Comment by rkratky** [comment]
@ibuziuk, I mean as much as you can. I'll be happy to help with it, but I don't have time to write it from scratch.

**Comment by ibuziuk** [comment]
Ok, I will take care of this issue

**Comment by ibuziuk** [comment]
@rkratky @supriya-bharadwaj @themr0c PR is ready for review

**Comment by ibuziuk** [comment]
PR has been merged - https://github.com/eclipse/che-docs/pull/729
Closing
