### ISSUE TITLE
Che 7 GA: Need to add docs about types of Che 7 plugins and Plugin registry

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che-docs#716]
Potential Structure:
- Existing types of plug-ins
- What is Plug-in registry
- What is the default Plug-in registry
- How to deploy and use custom Plug-in registry

Useful links:
- https://github.com/ibuziuk/docs/blob/master/che_plugin_brokers.adoc
- https://github.com/redhat-developer/rh-che/blob/master/dev-guide.adoc#che-plugin-registry
- https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L567

**Comment by rkratky** [comment]
@ibuziuk, we already have some content about this at https://www.eclipse.org/che/docs/che-7/extending-che.html#developing-che-theia-plug-ins-using-che_developing-che-theia-plug-ins

Do you have something different in mind?

**Comment by ibuziuk** [comment]
after talking with @l0rd it was decided that our team will not work on this issue and I think we can close it now.

**Comment by rkratky** [comment]
OK, but the question still stands: is this expected to be different content than what's already written? We have sections on both 'what's a plug-in' and about the plug-in registry. @l0rd?

**Comment by l0rd** [comment]
@rkratky this task was part of architecture section that should be an high level section with some diagrams and a short description of the Che components and of the workspace creation flow. Basically it should be something like [this google](https://docs.google.com/document/d/1HVVzuMZO7qVxEm6FosAhL5XuUzrMe2ooAAsvmnIWB6k/edit#heading=h.muu3eif52lwq) but updated. The sections you are referring are more hands-on but are still useful: there may be some update to do (the screenshots looks outdated for instance).

**Comment by themr0c** [comment]
@l0rd @rkratky @slemeur Please close this issue. The google document is stating "This doc has been converted to asciidoc Che Architectural Elements". Documentation has been published in https://www.eclipse.org/che/docs/che-7/che-workspaces-architecture/

**Comment by themr0c** [comment]
Thank you @ibuziuk!
