### ISSUE TITLE
Che 7 GA: high-level overview of a Plugin broker concept 

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che-docs#717]
Need to provide a high-level overview of a Plugin broker concept to the Che 7 GA docs.

Useful links:
- https://github.com/ibuziuk/docs/blob/master/che_plugin_brokers.adoc#plugin-brokers
- https://github.com/eclipse/che-plugin-broker/blob/master/README.md

**Comment by themr0c** [comment]
@l0rd @rkratky @slemeur Please close this issue.  Documentation has been published in https://www.eclipse.org/che/docs/che-7/che-workspaces-architecture/#che-plug-in-broker_che-workspace-components

**Comment by themr0c** [comment]
Thank you @ibuziuk!
