### ISSUE TITLE
[WIP] Update Using Version Control > Configuring GitHub OAuth section

### ISSUE THREAD

**Issue by supriya-bharadwaj** [eclipse/che-docs#731]
Edit the **Using Version Control** > **Configuring GitHub OAuth** section at https://www.eclipse.org/che/docs/che-6/version-control.html#configuring-github-oauth.

**Comment by themr0c** [comment]
I see the PR merged, this issue can probably get closed?

**Comment by supriya-bharadwaj** [comment]
Yes, @themr0c . Closing it. Thanks!
