### ISSUE TITLE
Add information about how to troubleshoot Che workspaces

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#739]
We should have a page explaining how a Che workspace can be troubleshoot. 
Where to find the logs depending on which platform Che is run on.
How to find logs about tools

**Comment by slemeur** [comment]
See started: https://docs.google.com/document/d/1puk0xDWJPaVz8VeKIMmr9EhL-rMnCE-yvxezXjPV1Hs/edit#

**Comment by themr0c** [comment]
This ticket can be closed. Its has been published in https://www.eclipse.org/che/docs/che-7/viewing-che-workspaces-logs/

**Comment by boczkowska** [comment]
The documentation on logs is published here: https://www.eclipse.org/che/docs/che-7/viewing-che-workspaces-logs/
