### ISSUE TITLE
[WIP]Update the "Using developer environments - workspaces" section for Che 7

### ISSUE THREAD

**Issue by supriya-bharadwaj** [eclipse/che-docs#748]
Update the "Using developer environments - workspaces" section at https://www.eclipse.org/che/docs/che-7/using-developer-environments-workspaces.html.

**Comment by supriya-bharadwaj** [comment]
PR: https://github.com/eclipse/che-docs/pull/752

**Comment by boczkowska** [comment]
Addressed in https://github.com/eclipse/che-docs/pull/752
