### ISSUE TITLE
Need to document the process of deployment Che on OpenShift

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che-docs#76]
Need to provide full documentation with instructions of deployment Che on OpenShift:

- [ ] Update configuration page of the setup section with information of how to enable openshift `io.fabric8` API for container management - https://www.eclipse.org/che/docs/setup/configuration/index.html
- [ ] Once CLI is extended with commands for running Che on OpenShift need to create a separate **OpenShift deploy** section with deployment instructions - https://www.eclipse.org/che/docs/openshift/config/index.html
- [ ] Make sure that documentation covers all relevant instructions / implementation details from **"Packaging Che to run on OpenShift"** epic - https://github.com/eclipse/che/issues/2847 
- [ ] Update Changelog

**Comment by bmicklea** [comment]
Hi @ibuziuk when do you think you'll be able to have these docs complete?  Going forward we're going to only be merging PRs with complete docs, release notes and changelog. In this case you got caught in the middle as we moved to the new policy so I understand why the docs aren't there yet but is someone working on them?  We should have them ASAP if they're going to be part of the release notes.

**Comment by ibuziuk** [comment]
@bmicklea hi, currently we are not working on the docs. Basically, OpenShift integration is still WIP, so it is kind of difficult to have meaningful docs now. As I recall, during the last call it was decided to provide all the docs for OpenShift integration once the issues from epic https://github.com/eclipse/che/issues/2847 are resolved.

**Comment by bmicklea** [comment]
Thanks for the clarification. In that case I don't think it makes sense to have this mentioned in the 5.2 release notes. Do you agree @ibuziuk?

**Comment by ibuziuk** [comment]
@bmicklea yes, I think it should be in release notes only once it feature complete

**Comment by bmicklea** [comment]
Thanks - I've updated the description of https://github.com/eclipse/che/pull/3798 to remove the Release Notes section.

**Comment by markbarks** [comment]
Hi, is there a work in progress available for this documentation by any chance? I'd love to start tinkering around with Che on OpenShift, but not sure where to get started.

**Comment by TylerJewell** [comment]
It is a document that we plan to do in May.  We have a long line of interested parties on this and we are scrambling to pull it together. We are still in engineering mode and things are not quite stable yet.  But it is coming soon.

**Comment by ibuziuk** [comment]
documentation is available under  https://www.eclipse.org/che/docs/che-7/che-quick-starts/ 
Closing
