### ISSUE TITLE
Documentation needed to get the server

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-docs#77]
With 5.1.0 we removed the `Ops perspective` and we moved the server part to the dashboard.

We need to update documentation on this. See the following support issue:
https://github.com/codenvy/codenvy/issues/1563

**Comment by slemeur** [comment]
Would appreciate your help on this @akurinnoy ;)

**Comment by themr0c** [comment]
We are closing this issues because we believe it is outdated. Please reopen if you believe the issue is still relevant.
