### ISSUE TITLE
[WIP] Review the Che 7 Administration guide for language, formatting, and typos.

### ISSUE THREAD

**Issue by supriya-bharadwaj** [eclipse/che-docs#776]
## Where to report issues?

This repository is not the primary repository of Eclipse Che.

🚨 Please don't submit new issues here. 🚨

All issues for Eclipse Che are managed at [https://github.com/eclipse/che/issues](https://github.com/eclipse/che/issues).

**Comment by supriya-bharadwaj** [comment]
PR at https://github.com/eclipse/che-docs/pull/777

**Comment by boczkowska** [comment]
Corresponding Jira issue: https://issues.redhat.com/browse/RHDEVDOCS-1238

**Comment by themr0c** [comment]
We are closing this issue as it is appearing outdated.
