### ISSUE TITLE
[WIP] Review the Che 7 Contributor guide for language, formatting, and typos

### ISSUE THREAD

**Issue by supriya-bharadwaj** [eclipse/che-docs#779]
## Where to report issues?

This repository is not the primary repository of Eclipse Che.

🚨 Please don't submit new issues here. 🚨

All issues for Eclipse Che are managed at [https://github.com/eclipse/che/issues](https://github.com/eclipse/che/issues).

**Comment by boczkowska** [comment]
This has been addressed in https://github.com/eclipse/che-docs/pull/780
