### ISSUE TITLE
Create CI jobs for che-docs

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse/che-docs#80]
We need a nightly and manual shipping CI job that pulls the docs from `eclipse/che-docs` and pushes them so that they're published at `eclipse.org/che/docs` or `eclipse.org/che/docs-version`.  

This job should also be able to be run manually at any other time.

### Step-by-step
Nightly:
1. Create new folders "nightly/docs" if not existing at  [https://eclipse.org/che/docs-version/nightly/docs]() .
1. Remove content of [https://eclipse.org/che/docs-version/nightly/docs/*]() .
2. Upload content of target/che-docs-\<version\>/ into https://eclipse.org/che/doc-version/nightly/docs/ .

Shipped version:
1. Create new folders "<version\>/docs" at [https://eclipse.org/che/docs-version/<version\>/docs]() . 
2. Upload content of target/che-docs-\<version\>/ into [https://eclipse.org/che/docs-version/<version\>/docs/]() .
3. Remove content of [https://eclipse.org/che/docs/*]() . 
4. Upload content of target/che-docs-\<version\>/ into https://eclipse.org/che/docs/.

**Comment by riuvshin** [comment]
it seems it is not possible do same for way what we did for codenvy. as @slemeur told me eclipse che site is under git repo so we can't build and upload docs.

I have not idea how to manage this.

**Comment by ajaygm** [comment]
This might be a very naive suggestion... 
Can https://pages.github.com/ be used for the purpose?

**Comment by JamesDrummond** [comment]
We do this manually each release and nightly is in product/che server so it is not needed.
