### ISSUE TITLE
Github top button is not working

### ISSUE THREAD

**Issue by benoitf** [eclipse/che-docs#96]
on https://www.eclipse.org/che/docs/index.html the button "Github" after Docs, Turorials, Openshift is redirecting is redirecting to a 404 error

![image](https://cloud.githubusercontent.com/assets/436777/22258096/91e5b8ea-e260-11e6-8a14-2a399a9a869f.png)

Also Openshift should be labeled OpenShift

**Comment by JamesDrummond** [comment]
being fixed in https://github.com/codenvy/codenvy-docs/tree/team-docs/src/main

**Comment by JamesDrummond** [comment]
OpenShift was already fixed. https://github.com/eclipse/che-docs/commit/f2dac28077f252e5fca51539ee8d61ad2aade8bf
